# -*- coding: utf-8 -*-
"""testeGrafico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e0vUzktGER1XRKQ2JrygRJkvIc8eGJ6S
"""

# -*- coding: utf-8 -*-
""" @author: Luiz """

import pandas as pd
import plotly.express as px
import streamlit as st
from openpyxl import *


df = pd.read_excel('HISTORICO.xlsx', sheet_name = 0)

#from google.colab import files
#df = files.upload()

titles = list(df['Title'].unique())
members = list(df['Members'].unique())

df['Due'] = pd.to_date(df['Due'], format='%Y/%m/%d' )


title = st.sidebar.selectbox('Escolha o Ticket', ['Todos'] + titles)
member = st.sidebar.selectbox('Escolha o Executor', ['Todos'] + members)

if(title != 'Todos'):
  st.text('Card: ' + title)
  df = df[df['Title'] == title]
#else:
#  st.text('Card: ' + title)
#  df = df[df['Title'] == title]

if(member != 'Todos'):
  st.text('Executor: ' + member)
  df = df[df['Members'] == member]

dfShow = df.groupby(by = ['Due']).sum()

st.text(dfShow.index)

#num_sequences vem do groupby
#grafico = px.line(dfShow, x=dfShow.index, y='num_sequences')
#grafico.update_layout(title = 'Cards do Trello')
#st.plotly_chart(grafico, use_container_width = True)

