# -*- coding: utf-8 -*-
"""testeGrafico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e0vUzktGER1XRKQ2JrygRJkvIc8eGJ6S
"""

# -*- coding: utf-8 -*-
""" @author: Luiz """

import pandas as pd
import plotly.express as px
import streamlit as st
from datetime import date
from openpyxl import *


df = pd.read_excel('HISTORICO.xlsx', sheet_name = 0)

#from google.colab import files
#df = files.upload()

titles = list(df['Title'].unique())
members = list(df['Members'].unique())

df['Due'] = pd.to_datetime(df['Due'], format='%Y/%m/%d' )


title = st.sidebar.selectbox('Escolha o Ticket', ['Todos'] + titles)
member = st.sidebar.selectbox('Escolha o Executor', ['Todos'] + members)

if(title != 'Todos'):
  st.text('Card: ' + title)
  df = df[df['Title'] == title]
#else:
#  st.text('Card: ' + title)
#  df = df[df['Title'] == title]

if(member != 'Todos'):
  st.text('Executor: ' + member)
  df = df[df['Members'] == member]

# original
# agrupa, cria o indice pela data e num_sequences, que é o totalizador
#num_sequences vem do groupby

df['nova_data'] = df['Due'].dt.strftime('%d-%m-%Y')
dfShow = df.groupby(by = ['nova_data']).sum()

grafico = px.line(dfShow, x=dfShow.index, y='num_sequences')
grafico.update_layout(title = 'Cards do Trello')
st.plotly_chart(grafico, use_container_width = True)


#Problema com a data
#não quer criar o indice, pq está date time e não estou conseguindo tirar a hora, na linha 27
#tentativas abaixo.

#st.text(dfShow.index)


#df['data_DD_MM_AAAA'] = df['Due'].dt.strftime('%d-%m-%Y')

#df['Due'] = pd.to_datetime(dataCard, errors = 'ignore', yearfirst = True, format='%Y/%m/%d' )
#dfShow = df.groupby(by = ['data_DD_MM_AAAA']).sum()

#st.text(dfShow.index)


